branches:
  only:
  - master

notifications:
  email:
    recipients:
      - timetchells@ibm.com
      # - devexbld@us.ibm.com
    on_success: change
    on_failure: change

os:
- linux

language: node_js
node_js:
- '10'

before_install:
#  Copy the LICENSE into the extension directory, so it is included in the build
- cp -v LICENSE dev
- cd dev
- npm i -g vsce
- npm ci
# Make sure compilation will succeed (vsce package won't show the compilation failures)
# Fail the build if compile fails
- npm run compile
# Run the linter, could switch to lint-f to not fail the build
- npm run lint

script:
- vsce package

after_success:
- export script_dir="../script/"
# copy the vsix to the upload script dir and cd into it
- export artifact_name="$(basename *.vsix)"
- mv -v $artifact_name $script_dir
- cd $script_dir
# will exit immediately if not a deploy build
- ./deploy.sh || >&2 echo "Deploy failed!"
